name: check-project-file

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install X2ProjectGenerator
      shell: pwsh
      run: |
        Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/robojumper/CovertInfiltration/tmp_ci_storage/X2ProjectGenerator.zip -OutFile X2ProjectGenerator.zip
        tar -xf X2ProjectGenerator.zip
    - name: Check project file
      shell: pwsh
      run: |
        .\X2ProjectGenerator.exe "CovertInfiltration\" --exclude-contents --verify-only
