name: check-project-file

on:
  push:
    branches:
      - master
      - ci_test
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install X2ProjectGenerator
      run: |
        curl -o X2ProjectGenerator.zip https://raw.githubusercontent.com/robojumper/CovertInfiltration/tmp_ci_storage/X2ProjectGenerator.zip
        unzip X2ProjectGenerator.zip -d .
        chmod +x X2ProjectGenerator.exe
    - name: Check project file
      run: |
        ./X2ProjectGenerator.exe CovertInfiltration/ --exclude-contents --verify-only
